
[build]
  publish = "dist"
  command = "npm run build"

# Define redirects so that client-side routing works with SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests"

# Environment variable configuration
[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.8.1"

# Split test for different deployment branches
[context.main]
  command = "npm run build"
  
[context.staging]
  command = "npm run build:staging"

# Custom domain configuration
[context.production]
  environment = { NODE_ENV = "production", SITE_URL = "https://mrcenpoche.xyz" }

# Custom domain setup
[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  baseUrl = "https://mrcenpoche.xyz"
  
# Optimize for production
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
