
[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Configuration du domaine personnalisé
[context.production]
  [context.production.environment]
    CUSTOM_DOMAIN = "mrcenpoche.xyz"
