
[build]
  publish = "dist"
  command = "npm run build"

# Define redirects so that client-side routing works with SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests"

# Environment variable configuration
[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.8.1"

# Split test for different deployment branches
[context.main]
  command = "npm ci --legacy-peer-deps && npm run build"
  
[context.staging]
  command = "npm ci --legacy-peer-deps && npm run build:staging"

# Custom domain configuration
[context.production]
  environment = { NODE_ENV = "production" }
  command = "npm ci --legacy-peer-deps && npm run build"

# Domain settings
[build.processing.html]
  pretty_urls = true

# Custom domain setup
[[plugins]]
  package = "@netlify/plugin-sitemap"

# Handle 404 errors gracefully
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
